emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    azure-resource-provider-folder: "./resource-manager"
    # `arm-resource-flattening` is only used for back-compat for specs existed on July 2024. All new service spec should NOT use this flag
    arm-resource-flattening: true
    emitter-output-dir: "{project-root}/../"
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/openapi.json"
    arm-types-dir: "{project-root}/../../common-types/resource-management"
    omit-unreachable-types: true
    use-read-only-status-schema: true
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
